package org.snoflo.repository;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;

import org.snoflo.domain.CsvFileRow;

public interface FinderRepository extends AppRepository {

    public void save(List<CsvFileRow> list, String fileName);

    default void createTable(String fileName) throws SQLException {

        StringBuilder tableSql = new StringBuilder();
        tableSql.append(" CREATE TABLE ")
                .append(fileName)
                .append("(")
                .append(" id INTEGER GENERATED BY DEFAULT AS IDENTITY, ")
                .append(" concept VARCHAR(255) NOT NULL UNIQUE,")
                .append("description VARCHAR(255) NOT NULL UNIQUE,")
                .append("keyword1 VARCHAR(255),")
                .append("keyword2 VARCHAR(255),")
                .append(" PRIMARY KEY (id)")
                .append(")");

        try (Connection conn = getDataSource().getConnection()) {
            PreparedStatement stmt = conn.prepareStatement(tableSql.toString());
            stmt.execute();
        }
    }

    default void truncateTable(String fileName) {

        StringBuilder sql = new StringBuilder();
        sql.append("TRUNCATE TABLE ")
                .append(fileName);

        try (Connection conn = getDataSource().getConnection()) {

            PreparedStatement stmt = conn.prepareStatement(sql.toString());
            stmt.execute();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

}
